### ISSUE TITLE
Panic in `DnsPacket::try_from`

### ISSUE THREAD

**Issue by rfuzz** [Akmot9/detect_dns_packet#1]
Hi,

During fuzz testing of the `DnsPacket::try_from` function, I encountered input that causes a panic:

```shell
echo "//+MA250cP8rlIAD" | base64 -d > crash.bin 
```

Here’s the test case:

```rust
use detect_dns_packet::DnsPacket;
use std::convert::TryFrom;

fn main() {
    if let Ok(data) = std::fs::read("crash.bin") {
        match DnsPacket::try_from(data.as_slice()) {
            Ok(packet) => {
                println!("{:?}", packet);
            }
            Err(e) => {
                println!("Error parsing DNS packet: {}", e);
            }
        }
    }
}
```

When running the program, it results in the following panic:

```shell
thread 'main' panicked at /home/ubuntu/detect_dns_packet/src/dns_queries/mod.rs:68:19:
index out of bounds: the len is 0 but the index is 0
stack backtrace:
   0: rust_begin_unwind
             at /rustc/ed04567ba1d5956d1080fb8121caa005ce059e12/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/ed04567ba1d5956d1080fb8121caa005ce059e12/library/core/src/panicking.rs:74:14
   2: core::panicking::panic_bounds_check
             at /rustc/ed04567ba1d5956d1080fb8121caa005ce059e12/library/core/src/panicking.rs:276:5
   3: detect_dns_packet::dns_queries::parse_name
             at /home/ubuntu/detect_dns_packet/src/dns_queries/mod.rs:68:19
   4: detect_dns_packet::dns_queries::DnsQuery::from_bytes
             at /home/ubuntu/detect_dns_packet/src/dns_queries/mod.rs:14:34
   5: detect_dns_packet::dns_queries::DnsQueries::from_bytes
             at /home/ubuntu/detect_dns_packet/src/dns_queries/mod.rs:48:26
   6: <detect_dns_packet::DnsPacket as core::convert::TryFrom<&[u8]>>::try_from
             at /home/ubuntu/detect_dns_packet/src/lib.rs:25:23
   7: detect_dns_packet_fuzz_target_test::main
             at ./src/main.rs:6:15
   8: core::ops::function::FnOnce::call_once
             at /rustc/ed04567ba1d5956d1080fb8121caa005ce059e12/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Version: `commit d56abadc4b5e29c4f24c02ce6064d22bacda133a`

**Comment by Akmot9** [comment]
Hello, I just saw your issue and I'm working on a fix ASAP. Let me know if it's better now.

**Comment by Akmot9** [comment]
the error is now well handled. 

starting fuzz testing
data: 12
Hexadecimal representation: ffff8c036e7470ff2b948003
try_from for dns_header: bytes: [255, 255, 140, 3, 110, 116, 112, 255, 43, 148, 128, 3], len: 12
transaction_id: 65535
flags: 35843
bytes: []
bytes len: 0
count: 28276
queries count: []
Error parsing DNS packet: Insufficient data: required 1 more bytes at offset 0, but only 0 bytes available
